export const HOMEPAGE_URL = '/'
export const HOMEPAGE_IMAGES_SRC = '/images/Homepage'
export const PRODUCTS_URL = '/products'
export const PRODUCTS_IMAGES_SRC = '/images/Products'
export const PRODUCTS_DETAILS_URL = '/products/:id'
export const PRODUCTS_DETAILS_IMAGES_SRC = '/images/ProductDetails'
export const CHECKOUT_URL = '/checkout'

export const ACCOUNT_PAGE_NESTED_PERSONAL_INFO = '/account/personal-info'
export const ACCOUNT_PAGE_NESTED_ORDERS = '/account/orders'
export const ACCOUNT_PAGE_NESTED_DELIVERY = '/account/delivery'
export const ACCOUNT_PAGE_NESTED_PASSWORD = '/account/password'

export const CHECKOUT_PAGE_NESTED_AUTH = '/checkout/auth'
export const CHECKOUT_PAGE_NESTED_DELIVERY = '/checkout/delivery'
export const CHECKOUT_PAGE_NESTED_SUMMARY = '/checkout/summary'

export const ACCOUNT_PAGE_RESET_PASSWORD_CURRENT_INPUT = 'current-input'
export const ACCOUNT_PAGE_RESET_PASSWORD_CURRENT_VALIDITY = 'current-valid'
export const ACCOUNT_PAGE_RESET_PASSWORD_NEW_INPUT = 'new-input'
export const ACCOUNT_PAGE_RESET_PASSWORD_NEW_VALIDITY = 'new-validity'
export const ACCOUNT_PAGE_RESET_PASSWORD_RETYPED_INPUT = 'retype-input'
export const ACCOUNT_PAGE_RESET_PASSWORD_RETYPES_VALIDITY = 'retype-valid'

export const SERVER = "http://localhost:5000"
export const SERVER_ROUTE_PRODUCTS = `${SERVER}/products`
export const SERVER_ROUTE_USERS = `${SERVER}/users`
export const SERVER_ROUTE_CONCEPTS = `${SERVER}/concepts`
export const SERVER_ROUTE_ORDERS = `${SERVER}/orders`

export const ADMIN_PAGE_PRODUCT_NAME_INPUT = 'name-input'
export const ADMIN_PAGE_PRODUCT_NAME_VALIDITY = 'name-valid'
export const ADMIN_PAGE_PRODUCT_PRICE_INPUT = 'price-input'
export const ADMIN_PAGE_PRODUCT_PRICE_VALIDITY = 'price-valid'
export const ADMIN_PAGE_PRODUCT_CONCEPT_INPUT = 'concept-input'
export const ADMIN_PAGE_PRODUCT_CONCEPT_VALIDITY = 'concept-valid'
export const ADMIN_PAGE_PRODUCT_SUB_INPUT = 'subcategories-input'
export const ADMIN_PAGE_PRODUCT_SUB_VALIDITY = 'subcategories-valid'
export const ADMIN_PAGE_PRODUCT_COLOR_INPUT = 'color-input'
export const ADMIN_PAGE_PRODUCT_COLOR_VALIDITY = 'color-valid'
export const ADMIN_PAGE_PRODUCT_MATERIAL_INPUT = 'material-input'
export const ADMIN_PAGE_PRODUCT_MATERIAL_VALIDITY = 'material-valid'
export const ADMIN_PAGE_PRODUCT_DESC_INPUT = 'description-input'
export const ADMIN_PAGE_PRODUCT_DESC_VALIDITY = 'description-valid'
export const ADMIN_PAGE_PRODUCT_IMG_INPUT = 'images-input'
export const ADMIN_PAGE_PRODUCT_IGM_VALIDITY = 'images-valid'
export const ADMIN_PAGE_PRODUCT_IMG_DELETE = 'images-delete'

export const CHECKOUT_PAGE_DELIVERY_NAME_INPUT = 'name-input'
export const CHECKOUT_PAGE_DELIVERY_NAME_VALIDITY = 'name-valid'
export const CHECKOUT_PAGE_DELIVERY_PHONE_INPUT = 'phone-input'
export const CHECKOUT_PAGE_DELIVERY_PHONE_VALIDITY = 'phone-valid'
export const CHECKOUT_PAGE_DELIVERY_ADDRESS_INPUT = 'address-input'
export const CHECKOUT_PAGE_DELIVERY_ADDRESS_VALIDITY = 'address-valid'

export const ACCOUNT_PAGE_PERSONAL_INFO_NAME_INPUT = 'name-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_NAME_VALIDITY = 'name-valid'
export const ACCOUNT_PAGE_PERSONAL_INFO_PHONE_INPUT = 'phone-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_PHONE_VALIDITY = 'phone-valid'
export const ACCOUNT_PAGE_PERSONAL_INFO_ADDRESS_INPUT = 'address-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_ADDRESS_VALIDITY = 'address-valid'
export const ACCOUNT_PAGE_PERSONAL_INFO_DOB_INPUT = 'dob-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_DOB_VALIDITY = 'dob-valid'
export const ACCOUNT_PAGE_PERSONAL_INFO_GENDER_INPUT = 'gender-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_GENDER_VALIDITY = 'gender-valid'
export const ACCOUNT_PAGE_PERSONAL_INFO_EMAIL_INPUT = 'email-input'
export const ACCOUNT_PAGE_PERSONAL_INFO_EMAIL_VALIDITY = 'email-valid'
